project:
  type: website

execute:
  freeze: auto

website:
  title: "SPACE GEOLOGY"
  page-footer:
    background: "#2c3e50"
    left:
      - text: "Edited by Florian Franziskakis, Sébastien Biass, Grégory Giuliani"
    center:
      - text: "More Information"
        href: info/license.qmd
    right:
      - text: "This course was built using Quarto"
        href: https://quarto.org/
      - icon: github
        href: https://github.com/unige-cgeom/SPACE-GEOLOGY
  navbar:
    background: "#2c3e50"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Course"
        href: course/chapter1_intro.qmd
      - text: "Report Template"
        href: report/report.qmd
      - text: "Cheat Sheets"
        href: cheat_sheets/cheat_sheet_chapter3_ex1_1.qmd

  sidebar:
    - title: "Course Chapters"
      contents:
        - course/chapter1_intro.qmd
        - course/chapter2_setup.qmd
        - course/chapter3_ex1_1.qmd
        - course/chapter4_ex1_2.qmd
        - course/chapter5_ex1_3.qmd
        - course/chapter6_ex2.qmd
    - title: "More Information"
      contents:
        - info/license.qmd
        - info/use_of_AI_declaration.qmd
    - title: "Cheat Sheets"
      contents:
        - cheat_sheets/cheat_sheet_chapter3_ex1_1.qmd