---
title: "Chapter II: Setting up your environment"
---

This chapter will help you get started with Python and set your environment up. There are a few different options
available to run the scripts that are provided in this course.

We will dedicate time during the first day to make sure all students have their environment and code editors installed on
their machines. It is advised however to try and install one before the course starts.

# Python
The SPACE-GEOLOGY course is based on Python, a widespread programming language used, amongst other things, to perform
data analysis. The Python ecosystem is made of libraries and packages designed to perform specific tasks. We will use
some of them that are focusing on data retrieval, analysis (spatial or non spatial) and visualization.

## Installing Python
Normally, most of the computers should have Python already installed, however we are going to use the Python 3.12 version,
which you can download from the [Python website](https://www.python.org/downloads/).

## Libraries

In this course, we will require the following libraries:

- [`xarray`](https://docs.xarray.dev/) A Python library for working with labeled multi-dimensional arrays, providing a Dataset structure that combines multiple variables sharing the same coordinate system.

- [`rioxarray`](https://corteva.github.io/rioxarray/) An extension of xarray that adds geospatial capabilities, enabling CRS-aware operations on raster datasets directly within the xarray framework.

- [`pandas`](https://pandas.pydata.org/) A Python library for data manipulation and analysis, providing a DataFrame structure that organizes tabular data with named columns and row indices.

- [`matplotlib`](https://matplotlib.org/) A comprehensive plotting library for creating static, animated, and interactive visualizations in Python.

- [`numpy`](https://numpy.org/) The fundamental package for efficient numerical computing in Python, providing fast arrays and mathematical operations.

- [`rasterio`](https://rasterio.readthedocs.io/) A Python library for reading, writing, and manipulating geospatial raster data using GDAL under the hood.

- [`requests`](https://requests.readthedocs.io/) A simple and elegant HTTP library for sending web requests and interacting with APIs.

- [`geopandas`](https://geopandas.org/) An extension of pandas for working with geospatial vector data, adding geometry support and spatial operations to DataFrames.

- [`os`](https://docs.python.org/3/library/os.html) A Python standard library module for interacting with the operating system, including file and directory management.

# Code editors

## Visual Studio (VS) Code

VS Code is a code editor developed by Microsoft. It is available for [Windows](https://code.visualstudio.com/docs/setup/windows),
[macOS](https://code.visualstudio.com/docs/setup/mac), or [Linux](https://code.visualstudio.com/docs/setup/linux).

You may follow the installation instructions associated to the operating system you are using, just make sure to have
the [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) also installed.


## PyCharm

PyCharm is an Integrated Development Environment (IDE) for Python that is also available for
[Windows](https://www.jetbrains.com/pycharm/download/?section=windows),
[macOS](https://www.jetbrains.com/pycharm/download/?section=mac), or [Linux](https://www.jetbrains.com/pycharm/download/?section=linux).

With its latest version, PyCharm now supports the integration of Jupyter Notebooks.


## Google Colab

Google Colab is an online service for running Jupyter Notebooks without the need for local code editor installation. It
can simply be accessed from [your browser](https://colab.research.google.com/) and already contains most of the required
libraries.

## QGIS Notebook

QGIS Notebook is a plugin that can be [installed in QGIS](https://plugins.qgis.org/plugins/qgis_notebook/) to run and
write notebooks. It uses the Python environment that comes with QGIS.